services:
    db:
        image: postgres:15
        container_name: postgres
        restart: unless-stopped
        ports:
            - "${DB_PORT:-5432}:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
